#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2022 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script for installing stdlib packages which are exposed as public APIs.
#
# Usage: install_pkgs.sh
#

## USER-DEFINED VARIABLES ##

# Define a list of packages which are exposed as public APIs:
pkgs=(
	"@stdlib/array-linspace"
	"@stdlib/blas-base-gaxpy"
	"@stdlib/datasets-afinn-111"
	"@stdlib/datasets-afinn-96"
	"@stdlib/datasets-anscombes-quartet"
	"@stdlib/datasets-cdc-nchs-us-births-1969-1988"
	"@stdlib/datasets-cdc-nchs-us-births-1994-2003"
	"@stdlib/datasets-herndon-venus-semidiameters"
	"@stdlib/datasets-nightingales-rose"
	"@stdlib/datasets-ssa-us-births-2000-2014"
	"@stdlib/datasets-suthaharan-single-hop-sensor-network"
	"@stdlib/math-base-special-abs"
	"@stdlib/math-base-special-abs2"
	"@stdlib/math-base-special-acos"
	"@stdlib/math-base-special-acosh"
	"@stdlib/math-base-special-acot"
	"@stdlib/math-base-special-acovercos"
	"@stdlib/math-base-special-acoversin"
	"@stdlib/math-base-special-acsc"
	"@stdlib/math-base-special-acsch"
	"@stdlib/math-base-special-ahavercos"
	"@stdlib/math-base-special-ahaversin"
	"@stdlib/math-base-special-asin"
	"@stdlib/math-base-special-asinh"
	"@stdlib/math-base-special-atan"
	"@stdlib/math-base-special-atan2"
	"@stdlib/math-base-special-atanh"
	"@stdlib/math-base-special-avercos"
	"@stdlib/math-base-special-aversin"
	"@stdlib/math-base-special-bernoulli"
	"@stdlib/math-base-special-besselj0"
	"@stdlib/math-base-special-besselj1"
	"@stdlib/math-base-special-bessely0"
	"@stdlib/math-base-special-bessely1"
	"@stdlib/math-base-special-beta"
	"@stdlib/math-base-special-betainc"
	"@stdlib/math-base-special-betaincinv"
	"@stdlib/math-base-special-betaln"
	"@stdlib/math-base-special-binet"
	"@stdlib/math-base-special-binomcoef"
	"@stdlib/math-base-special-binomcoefln"
	"@stdlib/math-base-special-boxcox"
	"@stdlib/math-base-special-boxcox1p"
	"@stdlib/math-base-special-boxcox1pinv"
	"@stdlib/math-base-special-boxcoxinv"
	"@stdlib/math-base-special-cbrt"
	"@stdlib/math-base-special-ceil"
	"@stdlib/math-base-special-ceil10"
	"@stdlib/math-base-special-ceil2"
	"@stdlib/math-base-special-ceilb"
	"@stdlib/math-base-special-ceiln"
	"@stdlib/math-base-special-ceilsd"
	"@stdlib/math-base-special-clamp"
	"@stdlib/math-base-special-copysign"
	"@stdlib/math-base-special-cos"
	"@stdlib/math-base-special-cosh"
	"@stdlib/math-base-special-cosm1"
	"@stdlib/math-base-special-cospi"
	"@stdlib/math-base-special-cot"
	"@stdlib/math-base-special-coth"
	"@stdlib/math-base-special-covercos"
	"@stdlib/math-base-special-coversin"
	"@stdlib/math-base-special-deg2rad"
	"@stdlib/math-base-special-digamma"
	"@stdlib/math-base-special-dirichlet-eta"
	"@stdlib/math-base-special-ellipe"
	"@stdlib/math-base-special-ellipk"
	"@stdlib/math-base-special-erf"
	"@stdlib/math-base-special-erfc"
	"@stdlib/math-base-special-erfcinv"
	"@stdlib/math-base-special-erfcx"
	"@stdlib/math-base-special-erfinv"
	"@stdlib/math-base-special-exp"
	"@stdlib/math-base-special-exp10"
	"@stdlib/math-base-special-exp2"
	"@stdlib/math-base-special-expit"
	"@stdlib/math-base-special-expm1"
	"@stdlib/math-base-special-expm1rel"
	"@stdlib/math-base-special-factorial"
	"@stdlib/math-base-special-factorialln"
	"@stdlib/math-base-special-falling-factorial"
	"@stdlib/math-base-special-fibonacci"
	"@stdlib/math-base-special-fibonacci-index"
	"@stdlib/math-base-special-flipsign"
	"@stdlib/math-base-special-floor"
	"@stdlib/math-base-special-floor10"
	"@stdlib/math-base-special-floor2"
	"@stdlib/math-base-special-floorb"
	"@stdlib/math-base-special-floorn"
	"@stdlib/math-base-special-floorsd"
	"@stdlib/math-base-special-fresnel"
	"@stdlib/math-base-special-fresnelc"
	"@stdlib/math-base-special-fresnels"
	"@stdlib/math-base-special-gamma"
	"@stdlib/math-base-special-gamma1pm1"
	"@stdlib/math-base-special-gammainc"
	"@stdlib/math-base-special-gammaincinv"
	"@stdlib/math-base-special-gammaln"
	"@stdlib/math-base-special-gcd"
	"@stdlib/math-base-special-hacovercos"
	"@stdlib/math-base-special-hacoversin"
	"@stdlib/math-base-special-havercos"
	"@stdlib/math-base-special-haversin"
	"@stdlib/math-base-special-heaviside"
	"@stdlib/math-base-special-hypot"
	"@stdlib/math-base-special-inv"
	"@stdlib/math-base-special-kronecker-delta"
	"@stdlib/math-base-special-ln"
	"@stdlib/math-base-special-log"
	"@stdlib/math-base-special-log10"
	"@stdlib/math-base-special-log1mexp"
	"@stdlib/math-base-special-log1p"
	"@stdlib/math-base-special-log1pexp"
	"@stdlib/math-base-special-log2"
	"@stdlib/math-base-special-logaddexp"
	"@stdlib/math-base-special-logit"
	"@stdlib/math-base-special-lucas"
	"@stdlib/math-base-special-modf"
	"@stdlib/math-base-special-negafibonacci"
	"@stdlib/math-base-special-negalucas"
	"@stdlib/math-base-special-nonfibonacci"
	"@stdlib/math-base-special-polygamma"
	"@stdlib/math-base-special-pow"
	"@stdlib/math-base-special-powm1"
	"@stdlib/math-base-special-rad2deg"
	"@stdlib/math-base-special-ramp"
	"@stdlib/math-base-special-riemann-zeta"
	"@stdlib/math-base-special-rising-factorial"
	"@stdlib/math-base-special-round"
	"@stdlib/math-base-special-round10"
	"@stdlib/math-base-special-round2"
	"@stdlib/math-base-special-roundb"
	"@stdlib/math-base-special-roundn"
	"@stdlib/math-base-special-roundsd"
	"@stdlib/math-base-special-sici"
	"@stdlib/math-base-special-signum"
	"@stdlib/math-base-special-sin"
	"@stdlib/math-base-special-sinc"
	"@stdlib/math-base-special-sincos"
	"@stdlib/math-base-special-sincospi"
	"@stdlib/math-base-special-sinh"
	"@stdlib/math-base-special-sinpi"
	"@stdlib/math-base-special-spence"
	"@stdlib/math-base-special-sqrt"
	"@stdlib/math-base-special-sqrt1pm1"
	"@stdlib/math-base-special-tan"
	"@stdlib/math-base-special-tanh"
	"@stdlib/math-base-special-tribonacci"
	"@stdlib/math-base-special-trigamma"
	"@stdlib/math-base-special-trunc"
	"@stdlib/math-base-special-trunc10"
	"@stdlib/math-base-special-trunc2"
	"@stdlib/math-base-special-truncb"
	"@stdlib/math-base-special-truncn"
	"@stdlib/math-base-special-vercos"
	"@stdlib/math-base-special-versin"
	"@stdlib/math-base-special-wrap"
	"@stdlib/math-base-special-xlog1py"
	"@stdlib/math-base-special-xlogy"
	"@stdlib/random-base-arcsine"
	"@stdlib/random-base-bernoulli"
	"@stdlib/random-base-beta"
	"@stdlib/random-base-betaprime"
	"@stdlib/random-base-binomial"
	"@stdlib/random-base-box-muller"
	"@stdlib/random-base-cauchy"
	"@stdlib/random-base-chi"
	"@stdlib/random-base-chisquare"
	"@stdlib/random-base-cosine"
	"@stdlib/random-base-discrete-uniform"
	"@stdlib/random-base-erlang"
	"@stdlib/random-base-exponential"
	"@stdlib/random-base-f"
	"@stdlib/random-base-frechet"
	"@stdlib/random-base-gamma"
	"@stdlib/random-base-geometric"
	"@stdlib/random-base-gumbel"
	"@stdlib/random-base-hypergeometric"
	"@stdlib/random-base-improved-ziggurat"
	"@stdlib/random-base-invgamma"
	"@stdlib/random-base-kumaraswamy"
	"@stdlib/random-base-laplace"
	"@stdlib/random-base-levy"
	"@stdlib/random-base-logistic"
	"@stdlib/random-base-lognormal"
	"@stdlib/random-base-minstd"
	"@stdlib/random-base-minstd-shuffle"
	"@stdlib/random-base-mt19937"
	"@stdlib/random-base-negative-binomial"
	"@stdlib/random-base-normal"
	"@stdlib/random-base-pareto-type1"
	"@stdlib/random-base-poisson"
	"@stdlib/random-base-rayleigh"
	"@stdlib/random-base-t"
	"@stdlib/random-base-triangular"
	"@stdlib/random-base-uniform"
	"@stdlib/random-base-weibull"
	"@stdlib/simulate-iter-sawtooth-wave"
	"@stdlib/stats-bartlett-test"
	"@stdlib/stats-base-cumax"
	"@stdlib/stats-base-dists-normal-entropy"
	"@stdlib/stats-base-dists-normal-pdf"
	"@stdlib/stats-base-max"
	"@stdlib/stats-base-mskmax"
	"@stdlib/string-camelcase"
	"@stdlib/string-capitalize"
	"@stdlib/string-constantcase"
	"@stdlib/string-kebabcase"
	"@stdlib/string-lowercase"
	"@stdlib/string-pascalcase"
	"@stdlib/string-snakecase"
	"@stdlib/string-startcase"
	"@stdlib/string-uncapitalize"
	"@stdlib/string-uppercase"
)

## SCRIPT ##

# Joins a list of strings.
#
# $1 - separator
# $* - list of strings to join
join() {
	local d=$1; shift; local f=$1; shift; printf %s "$f" "${@/#/$d}";
}

# Join the list of packages:
pkg_list=$(join " " "${pkgs[@]}")

# Install the packages:
npm install --save --save-dev ${pkg_list}
